import boto3
import json
BUCKET = 'transcibedemo'
FILE_TO_READ = 'transcribefromboto3trial3.json'
client = boto3.client('s3')
result = client.get_object(Bucket=BUCKET, Key=FILE_TO_READ)
text = result["Body"].read().decode()
result = json.loads(text)
print(result)
print(result['results']['transcripts'][0]['transcript'])
#{'jobName': 'transcribefromboto3trial3', 'accountId': '543540604913', 'results': {'transcripts': [{'transcript': 'Hi. This is simple text file for testing AWS transcribe service Hope it works.'}], 'items': [{'start_time': '0.04', 'end_time': '0.28', 'alternatives': [{'confidence': '0.9982', 'content': 'Hi'}], 'type': 'pronunciation'}, {'alternatives': [{'confidence': '0.0', 'content': '.'}], 'type': 'punctuation'}, {'start_time': '0.28', 'end_time': '0.49', 'alternatives': [{'confidence': '1.0', 'content': 'This'}], 'type': 'pronunciation'}, {'start_time': '0.49', 'end_time': '0.62', 'alternatives': [{'confidence': '1.0', 'content': 'is'}], 'type': 'pronunciation'}, {'start_time': '0.62', 'end_time': '1.04', 'alternatives': [{'confidence': '1.0', 'content': 'simple'}], 'type': 'pronunciation'}, {'start_time': '1.04', 'end_time': '1.44', 'alternatives': [{'confidence': '1.0', 'content': 'text'}], 'type': 'pronunciation'}, {'start_time': '1.44', 'end_time': '1.78', 'alternatives': [{'confidence': '1.0', 'content': 'file'}], 'type': 'pronunciation'}, {'start_time': '1.78', 'end_time': '1.95', 'alternatives': [{'confidence': '0.9994', 'content': 'for'}], 'type': 'pronunciation'}, {'start_time': '1.95', 'end_time': '2.45', 'alternatives': [{'confidence': '1.0', 'content': 'testing'}], 'type': 'pronunciation'}, {'start_time': '2.45', 'end_time': '3.25', 'alternatives': [{'confidence': '0.9253', 'content': 'AWS'}], 'type': 'pronunciation'}, {'start_time': '3.25', 'end_time': '3.84', 'alternatives': [{'confidence': '0.863', 'content': 'transcribe'}], 'type': 'pronunciation'}, {'start_time': '3.84', 'end_time': '4.5', 'alternatives': [{'confidence': '0.9999', 'content': 'service'}], 'type': 'pronunciation'}, {'start_time': '4.78', 'end_time': '5.12', 'alternatives': [{'confidence': '0.9938', 'content': 'Hope'}], 'type': 'pronunciation'}, {'start_time': '5.12', 'end_time': '5.26', 'alternatives': [{'confidence': '1.0', 'content': 'it'}], 'type': 'pronunciation'}, {'start_time': '5.26', 'end_time': '5.82', 'alternatives': [{'confidence': '1.0', 'content': 'works'}], 'type': 'pronunciation'}, {'alternatives': [{'confidence': '0.0', 'content': '.'}], 'type': 'punctuation'}]}, 'status': 'COMPLETED'}
#Hi. This is simple text file for testing AWS transcribe service Hope it works.
